### ISSUE TITLE
I wanted to suggest an idea

### ISSUE THREAD

**Issue by Paradox75831004** [kirpichyov/LC_EnemiesScanner#3]
Can you add the cost of the item and its duration to the configuration? It seems to me that the default cost should be 100, since the tool is quite strong and interesting. And the duration of the action is no more than 2 minutes (or I have a configuration setting)

Replace the current distance with another indicator, like a color - the closer the red icon or something like that. So that no one knows exactly how far the monster is. And make a limited detection radius - for example, 30m (in the configuration, this value can be changed if you add this feature)

**Comment by kirpichyovss** [comment]
Hi, @Paradox75831004 ! Thanks for your ideas, it sounds reasonable and useful to me. It would be a good idea to implement more configurations for the scanner as you suggested. I am going to introduce it in the next updates. According to your suggestions, I will add something like this:

- Ability to configure the cost of the scanner
- Ability to configure the battery size
- Implement cooldown along with configuration (?)
- Ability to configure if the exact distance should be hidden or shown (since LED indicators with colorful text and sounds already exist)
- Ability to limit the scanner radius and configure it

Thanks for reaching out!

**Comment by kirpichyov** [comment]
Hi, @Paradox75831004! Thanks for your ideas, it sounds reasonable and useful to me. It would be a good idea to implement more configurations for the scanner as you suggested. I am going to introduce it in the next updates. According to your suggestions, I will add something like this:

- Ability to configure the cost of the scanner
- Ability to configure the battery size
- Implement cooldown along with configuration (?)
- Ability to configure if the exact distance should be hidden or shown (since LED indicators with colorful text and sounds already exist)
- Ability to limit the scanner radius and configure it

Thanks for reaching out!

**Comment by kirpichyov** [comment]
Hi, @Paradox75831004 ! The new version of the game has been published and includes the discussed features except for the battery size config. Enjoy and thanks for your feedback and suggestions again!
