### ISSUE TITLE
[bug] Reserved slots

### ISSUE THREAD

**Issue by ytitnE** [kirpichyov/LC_EnemiesScanner#5]
When reserved slots is on, and you have the scanner on, when you have any item in any slot, the scanner light kinda stays on your screen, and the location of it depends on the item, shotgun being one that's noticeable. I don't know if its something you are aware of or unable to fix. Would be nice if you're able to disable the light entirely if you aren't able to fix it. Love the mod, appreciate the work

**Comment by kirpichyov** [comment]
Hi, @ytitnE! I will have a look at what causes this bug and if I can do something to fix it. Thanks for your feedback!

**Comment by ytitnE** [comment]
Appreciate the hard work! I will also say, sometimes its okay outside, if I recall correctly, but almost every time you go inside it will happen. Also, I was meaning like when the scanner is on, and your holding another item. Wanted to rephrase what I said before.

**Comment by kirpichyov** [comment]
Hi @ytitnE ! Looks like I was able to find an issue and fix it. The fix was published along with new features and improvements in the version `1.0.4`. It will take approximately half an hour now for Thunderstore to index the update so it will be available to download from the mod manager. If you need it sooner you could manually use the download button via [Thunderstore website](https://thunderstore.io/c/lethal-company/p/Kirpichyov/EnemiesScanner/versions/). Thanks for your feedback again and enjoy the update! Please feel free to re-open/open an issue if it's repro again.
